cors:
  originPatterns: http://localhost:8080 ,http://localhost:3000,https://www.erudio.com.br
file:
  upload-dir: C:/Users/franc/uploads
email:
  subject: "Default Subject"
  message: "Default Message"
spring:
  application:
    name: Rest-With-SpringBoot-Java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_springBoot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 247935Fr@
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:       
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smpt.starttls.required: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  level:
   # root: WARN 
    https.github.com.FrancoBorba: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
